### PR TITLE
rpi3: Add dtbo to disable bluetooth

### PR DESCRIPTION
**Pull request by grandpaul**
IOTMBL-1990: Remove bluetooth from DTB via generic overlay for
core-os/gateway and ensure the MBL BSP is compatible
    
Signed-off-by: Ying-Chun Liu (PaulLiu) <paulliu@debian.org>

### CODE REVIEW

**Comment by grandpaul** [comment]
I've use ENABLE_SERIAL_CONSOLE to include the dtbo.
But failed to build on jenkins due to mbed-fcc. 
http://jenkins.mbed-linux.arm.com/view/paulliu/job/paulliu-thud-gateway-bsp/4/

**Comment by grandpaul** [comment]
Hi. The latest jenkins builds.
http://jenkins.mbed-linux.arm.com/view/paulliu/job/paulliu-thud-gateway-bsp/5/
And it will apply disable-bt dtbo.
Please review this again?

**Comment by jonathanhaigh-arm** [comment]
@grandpaul, just to confirm: have you actually tested that the overlay gets applied when `ENABLE_SERIAL_CONSOLE` is set and that the overlay does not get applied when `ENABLE_SERIAL_CONSOLE` is not set?

**Comment by grandpaul** [comment]
ENABLE_SERIAL_CONSOLE = "1"
http://jenkins.mbed-linux.arm.com/view/paulliu/job/paulliu-thud-gateway-bsp-1/3/

ENABLE_SERIAL_CONSOLE = "0"
http://jenkins.mbed-linux.arm.com/view/paulliu/job/paulliu-thud-gateway-bsp-0/3/

ENABLE_SERIAL_CONSOLE unset
http://jenkins.mbed-linux.arm.com/view/paulliu/job/paulliu-thud-gateway-bsp/7/

Tested.
And as you can see the fitImage file in artifact. Using "mkimage -l" to list them. Only the first one containts the "fdt@overlays_pi3-disable-bt.dtbo".

**Comment by jonathanhaigh-arm** [comment]
Cool, thanks @grandpaul. Merging...

**Pull request merged**
