### PR TITLE
atf: switch SRC_URI to upstream repo and patches

### PR DESCRIPTION
**Pull request by niej**
Switch SRC_URI to upstream repo and use patches from linaro repo.

Signed-off-by: Jun Nie <jun.nie@linaro.org>

### CODE REVIEW

**Comment by niej** [comment]
Need @bryanodonoghue to help test imx6 before submitting to jenkins.

**Comment by jjohnson-arm** [comment]
> Need @bryanodonoghue to help test imx6 before submitting to jenkins.

As discussed - need to create images for imx6 and I can help test.

**Comment by jjohnson-arm** [comment]
Tested the imx6 image - updated IOTMBL-2446 with details.

**Comment by niej** [comment]
jenkins build and lava result. Only issue is imx8mm pelion update test is incomplete, but wifi test is OK. I am not sure what incomplete update test means.

http://jenkins.mbed-linux.arm.com/view/JunNie/job/jun-atf-patch/2/

http://e120856-lin.cambridge.arm.com/results.php?image_version=custom&image_number=-1&custom_version=jun-atf-patch&lava_query=&lava_owner=&failures=false&submitter=junnie01&sort=by_job

**Comment by jjohnson-arm** [comment]
From Petes review - there are 3 test failures:
* https://lava.mbedcloudtesting.com/scheduler/job/45379 appears to have struggled to flash the board and eventually timed out.
* https://lava.mbedcloudtesting.com/scheduler/job/45378 timed out while running xtest
* https://lava.mbedcloudtesting.com/scheduler/job/45377 fails some wifi tests but we have a ticket for that.

I suggest re-running the first two:
* https://lava.mbedcloudtesting.com/scheduler/job/46599
* https://lava.mbedcloudtesting.com/scheduler/job/46598

These have both passed.

**Comment by simonqhughes** [comment]
The following jenkins job was initiated after this PR was merged.

http://jenkins.mbed-linux.arm.com/view/mbl-builds/job/mbl-warrior-dev/311/console

**Pull request merged**
