### PR TITLE
 meta-mbl-bsp-common: u-boot: Set CONFIG_ENV_IS_NOWHERE=y

### PR DESCRIPTION
**Pull request by diego-sueiro**
Mbed Linux OS currently doesn't support u-boot storing the environment into any storage media.

### CODE REVIEW

**Comment by diego-sueiro** [comment]
Jenkins: http://jenkins.mbed-linux.arm.com/job/ds-warrior-dev/77/

**Comment by bryanodonoghue** [comment]
If i do "printenv ethaddr" on i.MX6 I get "ethaddr=00:1f:7b:10:09:a5" so I believe these boards have the ethernet MAC provisioned..

**Comment by diego-sueiro** [comment]
> Why are we patching the defconfig for u-boot-imx? Why isn't the config fragment enough?

Because the `imx8mmevk-mbl` machine makes usage of `UBOOT_CONFIG` variable that is also consumed by the `imx-boot` recipe.

In the `u-boot.inc` the merge config operation is only applied for machines that sets `UBOOT_MACHINE` instead of `UBOOT_CONFIG`.

**Comment by jonathanhaigh-arm** [comment]
> Because the `imx8mmevk-mbl` machine makes usage of `UBOOT_CONFIG` variable...

Mmmm. I don't like it, but okay... 

The BitBake looks fine so I too will defer to Bryan for approval.

**Comment by diego-sueiro** [comment]
> If i do "printenv ethaddr" on i.MX6 I get "ethaddr=00:1f:7b:10:09:a5" so I believe these boards have the ethernet MAC provisioned..

In my pico-imx6ul with CONFIG_ENV_IS_NOWHERE=y I get `ethaddr=00:1f:7b:11:1c:43`. I'm investigating to see how this ethaddr is being set.

**Comment by diego-sueiro** [comment]
> > If i do "printenv ethaddr" on i.MX6 I get "ethaddr=00:1f:7b:10:09:a5" so I believe these boards have the ethernet MAC provisioned..
> 
> In my pico-imx6ul with CONFIG_ENV_IS_NOWHERE=y I get `ethaddr=00:1f:7b:11:1c:43`. I'm investigating to see how this ethaddr is being set. And I can confirm that `CONFIG_NET_RANDOM_ETHADDR` is not set.

@bryanodonoghue, I turned on the [debug](https://git.linaro.org/landing-teams/working/mbl/u-boot.git/tree/drivers/net/fec_mxc.c?h=imx_v2018.03_4.14.78_1.0.0_ga-mbl&id=e9cb2c6d8a6227a189702ab2cfc7b1273689ddb2#n1123) in the imx fec driver and I can confirm that the eth addr is coming from the fuse registers.

**Pull request merged**
