### PR TITLE
optee-os: Add private ta certification key option

### PR DESCRIPTION
**Pull request by niej**
Add private ta certification key option so that default_key.pem can
be override to sign ta.

Trust application will be certificated so that it can be verified before run by optee. optee-os provides default key for the certification. But a private key should be used in for a product. This patch provides an option for developers to supply their own key.

Signed-off-by: Jun Nie <jun.nie@linaro.org>

### CODE REVIEW

**Comment by niej** [comment]
jenkins build: http://jenkins.mbed-linux.arm.com/view/JunNie/job/jun-add-optee-key-option/1/

**Comment by simonqhughes** [comment]
@niej Please can help with the following questions?
- please rebase so the dev branch is not out of date with the base branch
- please can you update the commit message to include the jira ticket under which this work was done
- please can you explain the rationale behind adding this key?
Thanks.

**Comment by niej** [comment]
please can you work with @petedyerarm and @diegorusso and @ollivainola to get a set of lava test results for this PR, and add a link to the test results to the PR?
 - Will do.
please rebase so the dev branch is not out of date with the base branch?
 - Jun: rebased.
please can you update the commit message to include the jira ticket under which this work was done?
 - Jun: jira number added.
please can you explain the rationale behind adding this key?
 - Jun: see updated PR description.
Thanks.

**Comment by simonqhughes** [comment]
@niej @petedyerarm @diegorusso I've stopped you jenkins test job here because it has the wrong config:

http://jenkins.mbed-linux.arm.com/view/JunNie/job/jun-add-optee-key-option/10/console

I've started this test job which is a clone of the BSP template to see if:
- we get all the build artifacts in artifactory
- we get the artifacts stored on jenkins as well as artifactory (so you can access them)
- we get a set of lava BSP test results for all boards

http://jenkins.mbed-linux.arm.com/job/sdh-jun-test-job/1/console

For reference the BSP test job template is here:

http://jenkins.mbed-linux.arm.com/view/simon/job/BSP_Team_PR_Submission_Template_Job/

Please create a new test job by cloning this template job, as your current job has the wrong config

**Comment by simonqhughes** [comment]
Here is link to the lava test results form simons job;

http://e120856-lin/results.php?server=prod&submitter=junnie01&image_version=custom&custom_version=sdh-jun-test-job&image_number=1

@niej Please could you add a similar link for your own job? thanks

**Comment by niej** [comment]
lava test report. All passed.

http://e120856-lin.cambridge.arm.com/results.php?server=prod&submitter=junnie01&image_version=custom&custom_version=jun-add-optee-key-option-2&image_number=1

**Comment by simonqhughes** [comment]
jenkins test job initiated after merge here:

http://jenkins.mbed-linux.arm.com/view/mbl-builds/job/mbl-warrior-dev/143/console

**Pull request merged**
