### PR TITLE
Fix i.mx8mm boot and reboot issue

### PR DESCRIPTION
**Pull request by bryanodonoghue**
This patch addresses to issues with the current i.MX8 boot.

- 1 An FDT apply error message for the DTB overlay
- 2 Slowness and hangs on boot and reboot

The second is a function of moving from ATF 1.5 to ATF 2.1 both the boot slowness and boot/reboot lockups are resolved by going back to ATF 1.5.

http://jenkins.mbed-linux.arm.com/job/bod-mbl-master/241/

### CODE REVIEW

**Comment by bryanodonoghue** [comment]
http://jenkins.mbed-linux.arm.com/job/bod-mbl-master/242

**Comment by simonqhughes** [comment]
Jenkins job at above link failed:

```
[2019-06-17T11:42:27.697Z] ERROR: atf-imx7d-pico-mbl-2.1+gitAUTOINC+kernel-r0 do_fetch: Fetcher failure: Unable to find revision 5d6615bbeca52d2b368c9d5f1186d44c4febc999 in branch master even from upstream



1029[2019-06-17T11:42:27.697Z] ERROR: atf-imx7d-pico-mbl-2.1+gitAUTOINC+kernel-r0 do_fetch: Fetcher failure for URL: 'git://git.linaro.org/landing-teams/working/mbl/arm-trusted-firmware.git;protocol=https;nobranch=1;name=atf'. Unable to fetch URL from any source.
```

Please could you investigate and fix? Thanks

**Comment by bryanodonoghue** [comment]
Once more
http://jenkins.mbed-linux.arm.com/job/bod-mbl-master/243/

**Comment by simonqhughes** [comment]
Please make a new jenkins job for this PR according to the instructions here:

https://confluence.arm.com/display/mbedlinux/Testing+for+BSP+Team+Developers

**Comment by bryanodonoghue** [comment]
http://jenkins.mbed-linux.arm.com/job/bod-mbl-master/244

**Pull request merged**
