### PR TITLE
merge feature-mbl-production-image branch into warrior-dev

### PR DESCRIPTION
**Pull request by diego-sueiro**
The list of commits and PRs:
7a4fd3c - #627
1d9dbfd - #635
858db63 - #649

### CODE REVIEW

**Comment by diego-sueiro** [comment]
Jenkins: http://jenkins.mbed-linux.arm.com/job/ds-warrior-dev/78/

**Comment by jonathanhaigh-arm** [comment]
Have all the commits already been reviewed in other PRs? Can you post links to these please?

**Comment by diego-sueiro** [comment]
> Have all the commits already been reviewed in other PRs? Can you post links to these please?

I updated the PR description with this information.

**Comment by jonathanhaigh-arm** [comment]
Thanks.

**Pull request merged**
