### PR TITLE
optee-os: imx6: switch SRC_URI to upstream

### PR DESCRIPTION
**Pull request by niej**
Switch imx6 SRC_URI to upstream and add staging patches in recipe.

Signed-off-by: Jun Nie <jun.nie@linaro.org>

### CODE REVIEW

**Comment by simonqhughes** [comment]
I see that @bryanodonoghue has approved this PR but its not clear appropriate testing been done? 

From an initial review I see that the changes only impact imx6ul. Has this been tested on this platform?

Please can we add links to testing/paste results/document testing done? Thanks

**Comment by simonqhughes** [comment]
I've discussed with @bryanodonoghue about his approval. He hasnt built and tested on target, which I think needs doing before this PR is accepted.

**Comment by simonqhughes** [comment]
@jjohnson-arm My current plan is to build and test this on your imx6ul. Please let me know if you have other plans.

**Comment by niej** [comment]
pass lava test.
http://jenkins.mbed-linux.arm.com/view/JunNie/job/jun-optee-patch/

http://e120856-lin.cambridge.arm.com/results.php?image_version=custom&image_number=-1&custom_version=jun-optee-patch&lava_query=&lava_owner=&failures=false&submitter=junnie01&sort=by_job

**Comment by simonqhughes** [comment]
Jun reports Jeremy has testing this on imx6ul as reported in this slack comment:

Jeremy Johnson [5:30 PM]
@jun.nie - jun-optee-patch/1/ boots fine - so best to put a lava job through

As the lava test results are fine for other platforms this can be merged.

**Comment by simonqhughes** [comment]
Initiated jenkins test job here after merging this pr:

http://jenkins.mbed-linux.arm.com/view/mbl-builds/job/mbl-warrior-dev/309/console

**Pull request merged**
