### PR TITLE
Bod warrior dev+imx6ul fit boot

### PR DESCRIPTION
**Pull request by bryanodonoghue**
This pull request enables FIT boot on imx6ul

Once applied it brings the IMX6UL to the same secure-boot level as the imx7 and imx8 boards.

It contains * 753776b - linux-fslc: imx6ul: Fix xtest and reboot error on pico6 (5 days ago) which is the subject of #699 as I need to verify OP-TEE in the built image and #699 is required for that.

Also I'm on a slightly earlier version of meta-mbl than Jun and Paul here so no doubt not all of my u-boot patches are currently in meta-mbl as individual patches.

https://git.linaro.org/landing-teams/working/mbl/u-boot.git/commit/?h=linaro-imx

* 319817bd42 - (HEAD -> linaro-imx, linaro-mbl/linaro-imx) cmd: image_info: Add checking of default FIT config (12 hours ago)
* ceae8c623f - pico-imx6ul: Define the name of the FIT bootscript subimage (2 days ago)
* fe9827490c - distro_bootcmd: Provide a define to select a FIT subimage (2 days ago)
* 6e88ef92c6 - pico-imx6ul_bl33: configs: Enable CONFIG_OF_LIBFDT_OVERLAY (3 days ago)
* 1352f5020b - pico-imx6ul_bl33: configs: Enable CONFIG_OF_LIBFDT (3 days ago)
* 8167dc8135 - pico-imx6ul_bl33: configs: Enable FIT as the boot.scr format (3 days ago)
* ee3b9f43df - pico-imx6ul: Reserve region of memory to OPTEE (3 weeks ago)
* 2ccdb910c0 - imx: imx6: arch_misc_init: Call into sec_init (4 weeks ago)
* e767d75b2a - imx: imx6: Add arch_misc_init (4 weeks ago)
* c1557c5c0e - mx7_common: Disjunct on CONFIG_OPTEE_SKIP_LOWLEVEL_INIT (4 weeks ago)
* 2b50b8c0da - pico-imx6ul: Add bl33 config (4 weeks ago)
* a77970701e - mx6_common: Share configs to skip low level init (5 weeks ago)
* 63c897678a - optee: Add CONFIG_OPTEE_SKIP_LOWLEVEL_INIT (5 weeks ago)
*   5fba74215f - Merge branch 'master' of git://git.denx.de/u-boot (6 weeks ago)

I've also found it necessary to modify the boot.cmd bootflow. This change should be replicated to the other boards.

The following flow

**Verifies the image - falling over to failsafe mode if the image is duff**
- iminfo 
- if test "$?" = "1"; then hab_failsafe; fi

**Extracts image components**
- imxtract ${scriptaddr}#conf@imx6ul-pico-pi.dtb fdt@imx6ul-pico-pi.dtb ${fdt_addr}
- imxtract ${scriptaddr}#conf@imx6ul-pico-pi.dtb kernel@1 ${loadaddr}

**Applies the OP-TEE provided DTB overlay**
- fdt apply ${fdtovaddr}

**Boots**
- bootz ${loadaddr}  ${scriptaddr}:ramdisk@1 ${fdt_addr}

**Boot Log**

**xtest**

### CODE REVIEW

**Comment by simonqhughes** [comment]
@bryanodonoghue do you have a jenkins test job for this PR, hopefully with some lava test results?

**Comment by bryanodonoghue** [comment]
I'll kick that off now @simonqhughes

**Comment by simonqhughes** [comment]
@bryanodonoghue Thanks for setting off the jenkins job (please ensure lava testing is enabled). I've discussed with Jezz and since time is of the essence I'll also kick off some aws builds to try and get this tested asap (by close of business today).

**Comment by bryanodonoghue** [comment]
http://jenkins.mbed-linux.arm.com/view/bod/job/bod-warrior-dev-00/

**Comment by simonqhughes** [comment]
Build and successfully booted images for supported devices including imx6ul. See attached boot logs for details.
[20190909_pr707_imx6ul_dev_image_boot_trace.txt](https://github.com/ARMmbed/meta-mbl/files/3591262/20190909_pr707_imx6ul_dev_image_boot_trace.txt)
[20190909_pr707_imx7d_pico_mbl_dev_image_boot_trace.txt](https://github.com/ARMmbed/meta-mbl/files/3591263/20190909_pr707_imx7d_pico_mbl_dev_image_boot_trace.txt)
[20190909_pr707_imx7s_warp_mbl_dev_image_boot_trace.txt](https://github.com/ARMmbed/meta-mbl/files/3591264/20190909_pr707_imx7s_warp_mbl_dev_image_boot_trace.txt)
[20190909_pr707_imx8mmevk_mbl_dev_image_boot_trace.txt](https://github.com/ARMmbed/meta-mbl/files/3591265/20190909_pr707_imx8mmevk_mbl_dev_image_boot_trace.txt)
[20190909_pr707_raspberrypi3_mbl_dev_image_boot_trace.txt](https://github.com/ARMmbed/meta-mbl/files/3591266/20190909_pr707_raspberrypi3_mbl_dev_image_boot_trace.txt)

**Comment by simonqhughes** [comment]
For reference, this is the lava testing link (still in progress)

http://e120856-lin.cambridge.arm.com/results.php?image_version=custom&image_number=-1&custom_version=bod-warrior-dev-00&lava_query=&lava_owner=&failures=false&submitter=bryodo01&sort=by_job

**Comment by bryanodonoghue** [comment]
Yay.

Nice way to end up. Please ping me with questions etc over the next week, I'm just faffing about at home anyway.

**Comment by simonqhughes** [comment]
Started this test job after merging this PR:

http://jenkins.mbed-linux.arm.com/view/mbl-builds/job/mbl-warrior-dev/320/console

**Pull request merged**
