### PR TITLE
Warrior dev imx8 fixup

### PR DESCRIPTION
**Pull request by bryanodonoghue**
Fixes two bugs on warrior-dev by cherry-picking from 0.7 to warrior-dev.

1. To fix an error with applying a DTB overlay
2. Reverts to ATF 1.5 from 2.1 while we further debug what is going wrong on 2.1

### CODE REVIEW

**Comment by bryanodonoghue** [comment]
http://jenkins.mbed-linux.arm.com/view/bod/job/bod-warrior-dev-01/1

**Comment by bryanodonoghue** [comment]
http://jenkins.mbed-linux.arm.com/view/bod/job/bod-warrior-dev-01/2

**Comment by bryanodonoghue** [comment]
http://jenkins.mbed-linux.arm.com/view/bod/job/bod-warrior-dev-01/3

**Comment by bryanodonoghue** [comment]
http://jenkins.mbed-linux.arm.com/view/bod/job/bod-warrior-dev-01/4

**Comment by diegorusso** [comment]
The build http://jenkins.mbed-linux.arm.com/view/bod/job/bod-warrior-dev-01/5/ succeeded and LAVA tests are passing.

**Comment by bryanodonoghue** [comment]
ping - can we merge this ?

**Pull request merged**
